name: CI/CD Pipeline with SonarQube

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd sports-matching-app
          npm ci

      - name: Run ESLint Check
        run: |
          cd sports-matching-app
          npx eslint . --max-warnings=0

      - name: Run Tests
        run: npm test

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=Find-A-Sports-Match-Frontend \
            -Dsonar.organization=brianbooth-15 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${SONAR_TOKEN}

      - name: SonarQube Quality Gate Check
        run: |
          echo "Checking SonarQube Quality Gate..."
          STATUS=$(curl -s -u "${SONAR_TOKEN}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Find-A-Sports-Match-Frontend" | jq -r .projectStatus.status)
          echo "Quality Gate Status: $STATUS"
          if [[ "$STATUS" != "OK" ]]; then
            echo "❌ Quality Gate Failed! Stopping deployment."
            exit 1
          fi
          echo "✅ Quality Gate Passed!"

  notify_amplify:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS Amplify Deploy
        run: |
          curl -X POST -d '{}' "${{ secrets.AMPLIFY_WEBHOOK_URL }}" -H "Content-Type:application/json"
